### ISSUE TITLE
WANT TO KNOW HOW I CAN DO IT ?

### ISSUE THREAD

**Issue by PIYUSH1525** [davevad93/davevad93#12]
CAN YOU PLESE TELL ME THE PROCESS HOW TO DO IT IN MY PROFILE ASLO > IT WILL BE VERY KIND OF YOU TO HELP ME

**Comment by Schrodingers-B0X** [comment]
Stop shouting

**Comment by 3377626947** [comment]
https://github.com/davevad93/davevad93/issues/12#issue-2527827615

**Comment by 3377626947** [comment]
0377626947

**Comment by davevad93** [comment]
Hey @PIYUSH1525 , you can create your own by checking my source code and editing it to your liking, it's quite straightforward, you just need to generate a `Personal Access Token` and add it as an environment variable in your repo settings under `Secrets and variables` -> `Actions` -> `New repository secret`. I've used `Ruby` but you can do the same with other languages like `Python` or `JavaScript`.

**Comment by Schrodingers-B0X** [comment]
First things first, thanks @davevad93 for the great script. So much cool stuff to learn on Github...

@PIYUSH1525 I'm relatively new to Github so this whole workflow setup was very new to me. There's lots of docs on Github to help you but I'll share the steps I took.

First have a look here to make your [Github App](https://docs.github.com/en/apps/creating-github-apps/about-creating-github-apps/about-creating-github-apps#about-github-apps)

For **Github App Name** I just gave it a generic name - "README UPDATER _blah blah_" .. I used my repo URL for the **Homepage URL** and saved it.

Then I needed to generate my [Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic) which it's scopes I checked the _parent_ **repo** checkbox. **Make sure to copy your generated token for the next step**

Now you'll need to add 2 [repository secrets](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository) to your repo. Add **TOKEN** , pasting your generated token into the "Value" form-box. Also add **USERNAME** with your Github username as the value.

There is still a lot to change to make this show your custom "About Me" , stats etc... I've already guided through the main steps needed... 

- To figure out the rest, a good way to see what I changed is to download [Notepad++](https://github.com/notepad-plus-plus/notepad-plus-plus) and install the [Compare+ Plugin](https://github.com/pnedev/comparePlus). 

- Download both [update_readme.rb](https://github.com/Schrodingers-B0X/Schrodingers-B0X/blob/main/scripts/update_readme.rb) file in my repo to the [original](https://github.com/davevad93/davevad93/blob/main/scripts/update_readme.rb) - _this has Italian and Spanish README files removed to make things easier_

- Download my [edited README](https://github.com/Schrodingers-B0X/Schrodingers-B0X/blob/main/README.md) and the [original](https://github.com/davevad93/davevad93/blob/main/README.md)

- Use the **Compare+** plugin in **Notepad++** to compare the files. It should give you a good idea of what needed changing.

If you're still stuck, each section of the review has a clickable link to take you to the original repo's and have instructions there....

Hope this helps other people too.

**Comment by Schrodingers-B0X** [comment]
Apologies @davevad93 I've not found a way to private message through here yet. Have you ever tried to create your own scripting for Max for Ableton Live yet?

I was considering some kind of randomiser script, potentially to randomise 64 bars with samples of a basic kick for 16-bars, then a kick and bass, or snare, hi-hats etc.. I'm a music production novice and thought it would be a cool idea to randomise samples to try get inspiration/new ideas quickly... Or a script to handle stem seperation which might be a bit more complex.
